name: Policy Test

on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.1

      - name: Get Kyverno
        run: |
          curl -sL `
            curl -sL https://api.github.com/repos/kyverno/kyverno/releases/latest \
            | jq -r '.assets[].browser_download_url' \
            | grep linux_x86_64 \
          ` | tar xvz -C /usr/local/bin

      - name: Kyverno test
        run: kyverno test .

